# Generated by Django 4.2.4 on 2023-09-01 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('salary_in_dollars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('access_recieved', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
